# Generated by Django 2.2.7 on 2019-12-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npm_mahasiswa', models.CharField(max_length=10, unique=True)),
                ('status_pembayaran', models.BooleanField(default=False)),
            ],
        ),
    ]
